// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WantTicketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FilmId int64 `protobuf:"varint,2,opt,name=filmId,proto3" json:"filmId,omitempty"`
	Type   int64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WantTicketReq) Reset() {
	*x = WantTicketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WantTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantTicketReq) ProtoMessage() {}

func (x *WantTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantTicketReq.ProtoReflect.Descriptor instead.
func (*WantTicketReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *WantTicketReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WantTicketReq) GetFilmId() int64 {
	if x != nil {
		return x.FilmId
	}
	return 0
}

func (x *WantTicketReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type WantTicketRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WantTicketRsp) Reset() {
	*x = WantTicketRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WantTicketRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantTicketRsp) ProtoMessage() {}

func (x *WantTicketRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantTicketRsp.ProtoReflect.Descriptor instead.
func (*WantTicketRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type TicketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FilmId    int64  `protobuf:"varint,2,opt,name=filmId,proto3" json:"filmId,omitempty"`
	MhId      int64  `protobuf:"varint,3,opt,name=mhId,proto3" json:"mhId,omitempty"`
	X         int64  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y         int64  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	StartTime string `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   string `protobuf:"bytes,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *TicketReq) Reset() {
	*x = TicketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketReq) ProtoMessage() {}

func (x *TicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketReq.ProtoReflect.Descriptor instead.
func (*TicketReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *TicketReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TicketReq) GetFilmId() int64 {
	if x != nil {
		return x.FilmId
	}
	return 0
}

func (x *TicketReq) GetMhId() int64 {
	if x != nil {
		return x.MhId
	}
	return 0
}

func (x *TicketReq) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TicketReq) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TicketReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TicketReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type TicketRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNumD int64 `protobuf:"varint,1,opt,name=orderNumD,proto3" json:"orderNumD,omitempty"`
}

func (x *TicketRsp) Reset() {
	*x = TicketRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketRsp) ProtoMessage() {}

func (x *TicketRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketRsp.ProtoReflect.Descriptor instead.
func (*TicketRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *TicketRsp) GetOrderNumD() int64 {
	if x != nil {
		return x.OrderNumD
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum   string `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	OrderPrice string `protobuf:"bytes,2,opt,name=orderPrice,proto3" json:"orderPrice,omitempty"`
	CreateAt   string `protobuf:"bytes,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	PayAt      string `protobuf:"bytes,4,opt,name=payAt,proto3" json:"payAt,omitempty"`
	MhId       int64  `protobuf:"varint,5,opt,name=mhId,proto3" json:"mhId,omitempty"`
	UserId     int64  `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`
	MovieId    int64  `protobuf:"varint,7,opt,name=movieId,proto3" json:"movieId,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *Order) GetOrderPrice() string {
	if x != nil {
		return x.OrderPrice
	}
	return ""
}

func (x *Order) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Order) GetPayAt() string {
	if x != nil {
		return x.PayAt
	}
	return ""
}

func (x *Order) GetMhId() int64 {
	if x != nil {
		return x.MhId
	}
	return 0
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type MovieTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilmName  string `protobuf:"bytes,1,opt,name=filmName,proto3" json:"filmName,omitempty"`
	StartTime string `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Cinema    string `protobuf:"bytes,3,opt,name=cinema,proto3" json:"cinema,omitempty"`
	OrderNum  string `protobuf:"bytes,4,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
}

func (x *MovieTicket) Reset() {
	*x = MovieTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieTicket) ProtoMessage() {}

func (x *MovieTicket) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieTicket.ProtoReflect.Descriptor instead.
func (*MovieTicket) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *MovieTicket) GetFilmName() string {
	if x != nil {
		return x.FilmName
	}
	return ""
}

func (x *MovieTicket) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *MovieTicket) GetCinema() string {
	if x != nil {
		return x.Cinema
	}
	return ""
}

func (x *MovieTicket) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type LookOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *LookOrdersReq) Reset() {
	*x = LookOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookOrdersReq) ProtoMessage() {}

func (x *LookOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookOrdersReq.ProtoReflect.Descriptor instead.
func (*LookOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *LookOrdersReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LookOrdersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieTickets []*MovieTicket `protobuf:"bytes,1,rep,name=movieTickets,proto3" json:"movieTickets,omitempty"`
}

func (x *LookOrdersRsp) Reset() {
	*x = LookOrdersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookOrdersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookOrdersRsp) ProtoMessage() {}

func (x *LookOrdersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookOrdersRsp.ProtoReflect.Descriptor instead.
func (*LookOrdersRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *LookOrdersRsp) GetMovieTickets() []*MovieTicket {
	if x != nil {
		return x.MovieTickets
	}
	return nil
}

type PayOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Phone    int64  `protobuf:"varint,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *PayOrderReq) Reset() {
	*x = PayOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReq) ProtoMessage() {}

func (x *PayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReq.ProtoReflect.Descriptor instead.
func (*PayOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *PayOrderReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *PayOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderReq) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

type PayOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PayOrderRsp) Reset() {
	*x = PayOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRsp) ProtoMessage() {}

func (x *PayOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRsp.ProtoReflect.Descriptor instead.
func (*PayOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

type UndoOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *UndoOrderReq) Reset() {
	*x = UndoOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoOrderReq) ProtoMessage() {}

func (x *UndoOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoOrderReq.ProtoReflect.Descriptor instead.
func (*UndoOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *UndoOrderReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type UndoOrderRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UndoOrderRsp) Reset() {
	*x = UndoOrderRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UndoOrderRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoOrderRsp) ProtoMessage() {}

func (x *UndoOrderRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoOrderRsp.ProtoReflect.Descriptor instead.
func (*UndoOrderRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

type GetOrderMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNum string `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetOrderMessageReq) Reset() {
	*x = GetOrderMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderMessageReq) ProtoMessage() {}

func (x *GetOrderMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderMessageReq.ProtoReflect.Descriptor instead.
func (*GetOrderMessageReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderMessageReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *GetOrderMessageReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderMessageRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticketdetail *TicketDetail `protobuf:"bytes,1,opt,name=ticketdetail,proto3" json:"ticketdetail,omitempty"`
}

func (x *GetOrderMessageRsp) Reset() {
	*x = GetOrderMessageRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderMessageRsp) ProtoMessage() {}

func (x *GetOrderMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderMessageRsp.ProtoReflect.Descriptor instead.
func (*GetOrderMessageRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderMessageRsp) GetTicketdetail() *TicketDetail {
	if x != nil {
		return x.Ticketdetail
	}
	return nil
}

type TicketDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilmName      string  `protobuf:"bytes,1,opt,name=filmName,proto3" json:"filmName,omitempty"`
	FilmImg       string  `protobuf:"bytes,2,opt,name=filmImg,proto3" json:"filmImg,omitempty"`
	StartTime     string  `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string  `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	CinemaName    string  `protobuf:"bytes,5,opt,name=cinemaName,proto3" json:"cinemaName,omitempty"`
	MhName        string  `protobuf:"bytes,6,opt,name=mhName,proto3" json:"mhName,omitempty"`
	Seat          string  `protobuf:"bytes,7,opt,name=seat,proto3" json:"seat,omitempty"`
	OrderNum      string  `protobuf:"bytes,8,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	CinemaAddress string  `protobuf:"bytes,9,opt,name=cinemaAddress,proto3" json:"cinemaAddress,omitempty"`
	Price         float32 `protobuf:"fixed32,10,opt,name=price,proto3" json:"price,omitempty"`
	CreateAt      string  `protobuf:"bytes,11,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Phone         int64   `protobuf:"varint,12,opt,name=phone,proto3" json:"phone,omitempty"`
	CinemaPhone   int64   `protobuf:"varint,13,opt,name=cinemaPhone,proto3" json:"cinemaPhone,omitempty"`
}

func (x *TicketDetail) Reset() {
	*x = TicketDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketDetail) ProtoMessage() {}

func (x *TicketDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketDetail.ProtoReflect.Descriptor instead.
func (*TicketDetail) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *TicketDetail) GetFilmName() string {
	if x != nil {
		return x.FilmName
	}
	return ""
}

func (x *TicketDetail) GetFilmImg() string {
	if x != nil {
		return x.FilmImg
	}
	return ""
}

func (x *TicketDetail) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TicketDetail) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TicketDetail) GetCinemaName() string {
	if x != nil {
		return x.CinemaName
	}
	return ""
}

func (x *TicketDetail) GetMhName() string {
	if x != nil {
		return x.MhName
	}
	return ""
}

func (x *TicketDetail) GetSeat() string {
	if x != nil {
		return x.Seat
	}
	return ""
}

func (x *TicketDetail) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *TicketDetail) GetCinemaAddress() string {
	if x != nil {
		return x.CinemaAddress
	}
	return ""
}

func (x *TicketDetail) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketDetail) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *TicketDetail) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *TicketDetail) GetCinemaPhone() int64 {
	if x != nil {
		return x.CinemaPhone
	}
	return 0
}

type LookAlreadyOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *LookAlreadyOrdersReq) Reset() {
	*x = LookAlreadyOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookAlreadyOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookAlreadyOrdersReq) ProtoMessage() {}

func (x *LookAlreadyOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookAlreadyOrdersReq.ProtoReflect.Descriptor instead.
func (*LookAlreadyOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *LookAlreadyOrdersReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LookAlreadyOrdersRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMovie   int64           `protobuf:"varint,1,opt,name=totalMovie,proto3" json:"totalMovie,omitempty"`
	OneNoComment int64           `protobuf:"varint,2,opt,name=oneNoComment,proto3" json:"oneNoComment,omitempty"`
	Movies       []*AlreadyMovie `protobuf:"bytes,3,rep,name=movies,proto3" json:"movies,omitempty"`
}

func (x *LookAlreadyOrdersRsp) Reset() {
	*x = LookAlreadyOrdersRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookAlreadyOrdersRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookAlreadyOrdersRsp) ProtoMessage() {}

func (x *LookAlreadyOrdersRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookAlreadyOrdersRsp.ProtoReflect.Descriptor instead.
func (*LookAlreadyOrdersRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *LookAlreadyOrdersRsp) GetTotalMovie() int64 {
	if x != nil {
		return x.TotalMovie
	}
	return 0
}

func (x *LookAlreadyOrdersRsp) GetOneNoComment() int64 {
	if x != nil {
		return x.OneNoComment
	}
	return 0
}

func (x *LookAlreadyOrdersRsp) GetMovies() []*AlreadyMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type AlreadyMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilmImg    string   `protobuf:"bytes,1,opt,name=filmImg,proto3" json:"filmImg,omitempty"`
	FilmName   string   `protobuf:"bytes,2,opt,name=filmName,proto3" json:"filmName,omitempty"`
	Time       string   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Director   string   `protobuf:"bytes,4,opt,name=director,proto3" json:"director,omitempty"`
	ActorNames []string `protobuf:"bytes,5,rep,name=actorNames,proto3" json:"actorNames,omitempty"`
	OrderNum   string   `protobuf:"bytes,6,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
}

func (x *AlreadyMovie) Reset() {
	*x = AlreadyMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlreadyMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlreadyMovie) ProtoMessage() {}

func (x *AlreadyMovie) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlreadyMovie.ProtoReflect.Descriptor instead.
func (*AlreadyMovie) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *AlreadyMovie) GetFilmImg() string {
	if x != nil {
		return x.FilmImg
	}
	return ""
}

func (x *AlreadyMovie) GetFilmName() string {
	if x != nil {
		return x.FilmName
	}
	return ""
}

func (x *AlreadyMovie) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AlreadyMovie) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *AlreadyMovie) GetActorNames() []string {
	if x != nil {
		return x.ActorNames
	}
	return nil
}

func (x *AlreadyMovie) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type OrderCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Score          int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	CommentContent string `protobuf:"bytes,3,opt,name=commentContent,proto3" json:"commentContent,omitempty"`
	OrderNum       string `protobuf:"bytes,4,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	MovieId        int64  `protobuf:"varint,5,opt,name=movieId,proto3" json:"movieId,omitempty"`
}

func (x *OrderCommentReq) Reset() {
	*x = OrderCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommentReq) ProtoMessage() {}

func (x *OrderCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommentReq.ProtoReflect.Descriptor instead.
func (*OrderCommentReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

func (x *OrderCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderCommentReq) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *OrderCommentReq) GetCommentContent() string {
	if x != nil {
		return x.CommentContent
	}
	return ""
}

func (x *OrderCommentReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

func (x *OrderCommentReq) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type OrderCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderCommentRsp) Reset() {
	*x = OrderCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCommentRsp) ProtoMessage() {}

func (x *OrderCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCommentRsp.ProtoReflect.Descriptor instead.
func (*OrderCommentRsp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{19}
}

var File_order_proto protoreflect.FileDescriptor

var file_order_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x0d, 0x57, 0x61, 0x6e, 0x74, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x57, 0x61, 0x6e,
	0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x73, 0x70, 0x22, 0xa3, 0x01, 0x0a, 0x09, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x68, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x68, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x29, 0x0a, 0x09, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x44, 0x22, 0xbb, 0x01, 0x0a, 0x05,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x79, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61,
	0x79, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x68, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x6d, 0x68, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x7b, 0x0a, 0x0b, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x27, 0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x47, 0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x73, 0x70,
	0x12, 0x36, 0x0a, 0x0c, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x57, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70,
	0x22, 0x28, 0x0a, 0x0c, 0x55, 0x6e, 0x64, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x55, 0x6e,
	0x64, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x22, 0x48, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0c, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x22, 0xf4, 0x02, 0x0a, 0x0c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x6d, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x4c, 0x6f,
	0x6f, 0x6b, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x14, 0x4c,
	0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x4e, 0x6f, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6f, 0x6e, 0x65, 0x4e, 0x6f,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x06, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x73, 0x22, 0xb0, 0x01, 0x0a, 0x0c, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x6d, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x6d, 0x49, 0x6d, 0x67, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x9d, 0x01, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x32, 0xf6, 0x03, 0x0a, 0x0f, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78, 0x74, 0x12, 0x38,
	0x0a, 0x0a, 0x57, 0x61, 0x6e, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x08, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x09, 0x55, 0x6e,
	0x64, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x55, 0x6e, 0x64, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x73,
	0x70, 0x12, 0x47, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0a, 0x4c, 0x6f,
	0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x11, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c,
	0x6f, 0x6f, 0x6b, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x73, 0x70, 0x42, 0x04, 0x5a, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData = file_order_proto_rawDesc
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_proto_rawDescData)
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_order_proto_goTypes = []interface{}{
	(*WantTicketReq)(nil),        // 0: order.WantTicketReq
	(*WantTicketRsp)(nil),        // 1: order.WantTicketRsp
	(*TicketReq)(nil),            // 2: order.TicketReq
	(*TicketRsp)(nil),            // 3: order.TicketRsp
	(*Order)(nil),                // 4: order.Order
	(*MovieTicket)(nil),          // 5: order.MovieTicket
	(*LookOrdersReq)(nil),        // 6: order.LookOrdersReq
	(*LookOrdersRsp)(nil),        // 7: order.LookOrdersRsp
	(*PayOrderReq)(nil),          // 8: order.PayOrderReq
	(*PayOrderRsp)(nil),          // 9: order.PayOrderRsp
	(*UndoOrderReq)(nil),         // 10: order.UndoOrderReq
	(*UndoOrderRsp)(nil),         // 11: order.UndoOrderRsp
	(*GetOrderMessageReq)(nil),   // 12: order.GetOrderMessageReq
	(*GetOrderMessageRsp)(nil),   // 13: order.GetOrderMessageRsp
	(*TicketDetail)(nil),         // 14: order.TicketDetail
	(*LookAlreadyOrdersReq)(nil), // 15: order.LookAlreadyOrdersReq
	(*LookAlreadyOrdersRsp)(nil), // 16: order.LookAlreadyOrdersRsp
	(*AlreadyMovie)(nil),         // 17: order.AlreadyMovie
	(*OrderCommentReq)(nil),      // 18: order.OrderCommentReq
	(*OrderCommentRsp)(nil),      // 19: order.OrderCommentRsp
}
var file_order_proto_depIdxs = []int32{
	5,  // 0: order.LookOrdersRsp.movieTickets:type_name -> order.MovieTicket
	14, // 1: order.GetOrderMessageRsp.ticketdetail:type_name -> order.TicketDetail
	17, // 2: order.LookAlreadyOrdersRsp.movies:type_name -> order.AlreadyMovie
	0,  // 3: order.OrderServiceExt.WantTicket:input_type -> order.WantTicketReq
	2,  // 4: order.OrderServiceExt.Ticket:input_type -> order.TicketReq
	8,  // 5: order.OrderServiceExt.PayOrder:input_type -> order.PayOrderReq
	10, // 6: order.OrderServiceExt.UndoOrder:input_type -> order.UndoOrderReq
	12, // 7: order.OrderServiceExt.GetOrderMessage:input_type -> order.GetOrderMessageReq
	6,  // 8: order.OrderServiceExt.LookOrders:input_type -> order.LookOrdersReq
	15, // 9: order.OrderServiceExt.LookAlreadyOrders:input_type -> order.LookAlreadyOrdersReq
	18, // 10: order.OrderServiceExt.OrderComment:input_type -> order.OrderCommentReq
	1,  // 11: order.OrderServiceExt.WantTicket:output_type -> order.WantTicketRsp
	3,  // 12: order.OrderServiceExt.Ticket:output_type -> order.TicketRsp
	9,  // 13: order.OrderServiceExt.PayOrder:output_type -> order.PayOrderRsp
	11, // 14: order.OrderServiceExt.UndoOrder:output_type -> order.UndoOrderRsp
	13, // 15: order.OrderServiceExt.GetOrderMessage:output_type -> order.GetOrderMessageRsp
	7,  // 16: order.OrderServiceExt.LookOrders:output_type -> order.LookOrdersRsp
	16, // 17: order.OrderServiceExt.LookAlreadyOrders:output_type -> order.LookAlreadyOrdersRsp
	19, // 18: order.OrderServiceExt.OrderComment:output_type -> order.OrderCommentRsp
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WantTicketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WantTicketRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookOrdersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UndoOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UndoOrderRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderMessageRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookAlreadyOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookAlreadyOrdersRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlreadyMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_rawDesc = nil
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceExtClient is the client API for OrderServiceExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceExtClient interface {
	//想看
	WantTicket(ctx context.Context, in *WantTicketReq, opts ...grpc.CallOption) (*WantTicketRsp, error)
	//下单
	Ticket(ctx context.Context, in *TicketReq, opts ...grpc.CallOption) (*TicketRsp, error)
	//支付
	PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderRsp, error)
	//取消订单
	UndoOrder(ctx context.Context, in *UndoOrderReq, opts ...grpc.CallOption) (*UndoOrderRsp, error)
	// 根据订单号获取电影票的信息
	GetOrderMessage(ctx context.Context, in *GetOrderMessageReq, opts ...grpc.CallOption) (*GetOrderMessageRsp, error)
	//查看所有电影票
	LookOrders(ctx context.Context, in *LookOrdersReq, opts ...grpc.CallOption) (*LookOrdersRsp, error)
	//查看所有看过的电影票
	LookAlreadyOrders(ctx context.Context, in *LookAlreadyOrdersReq, opts ...grpc.CallOption) (*LookAlreadyOrdersRsp, error)
	// 进行评分
	OrderComment(ctx context.Context, in *OrderCommentReq, opts ...grpc.CallOption) (*OrderCommentRsp, error)
}

type orderServiceExtClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceExtClient(cc grpc.ClientConnInterface) OrderServiceExtClient {
	return &orderServiceExtClient{cc}
}

func (c *orderServiceExtClient) WantTicket(ctx context.Context, in *WantTicketReq, opts ...grpc.CallOption) (*WantTicketRsp, error) {
	out := new(WantTicketRsp)
	err := c.cc.Invoke(ctx, "/order.OrderServiceExt/WantTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceExtClient) Ticket(ctx context.Context, in *TicketReq, opts ...grpc.CallOption) (*TicketRsp, error) {
	out := new(TicketRsp)
	err := c.cc.Invoke(ctx, "/order.OrderServiceExt/Ticket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceExtClient) PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderRsp, error) {
	out := new(PayOrderRsp)
	err := c.cc.Invoke(ctx, "/order.OrderServiceExt/PayOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceExtClient) UndoOrder(ctx context.Context, in *UndoOrderReq, opts ...grpc.CallOption) (*UndoOrderRsp, error) {
	out := new(UndoOrderRsp)
	err := c.cc.Invoke(ctx, "/order.OrderServiceExt/UndoOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceExtClient) GetOrderMessage(ctx context.Context, in *GetOrderMessageReq, opts ...grpc.CallOption) (*GetOrderMessageRsp, error) {
	out := new(GetOrderMessageRsp)
	err := c.cc.Invoke(ctx, "/order.OrderServiceExt/GetOrderMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceExtClient) LookOrders(ctx context.Context, in *LookOrdersReq, opts ...grpc.CallOption) (*LookOrdersRsp, error) {
	out := new(LookOrdersRsp)
	err := c.cc.Invoke(ctx, "/order.OrderServiceExt/LookOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceExtClient) LookAlreadyOrders(ctx context.Context, in *LookAlreadyOrdersReq, opts ...grpc.CallOption) (*LookAlreadyOrdersRsp, error) {
	out := new(LookAlreadyOrdersRsp)
	err := c.cc.Invoke(ctx, "/order.OrderServiceExt/LookAlreadyOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceExtClient) OrderComment(ctx context.Context, in *OrderCommentReq, opts ...grpc.CallOption) (*OrderCommentRsp, error) {
	out := new(OrderCommentRsp)
	err := c.cc.Invoke(ctx, "/order.OrderServiceExt/OrderComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceExtServer is the server API for OrderServiceExt service.
type OrderServiceExtServer interface {
	//想看
	WantTicket(context.Context, *WantTicketReq) (*WantTicketRsp, error)
	//下单
	Ticket(context.Context, *TicketReq) (*TicketRsp, error)
	//支付
	PayOrder(context.Context, *PayOrderReq) (*PayOrderRsp, error)
	//取消订单
	UndoOrder(context.Context, *UndoOrderReq) (*UndoOrderRsp, error)
	// 根据订单号获取电影票的信息
	GetOrderMessage(context.Context, *GetOrderMessageReq) (*GetOrderMessageRsp, error)
	//查看所有电影票
	LookOrders(context.Context, *LookOrdersReq) (*LookOrdersRsp, error)
	//查看所有看过的电影票
	LookAlreadyOrders(context.Context, *LookAlreadyOrdersReq) (*LookAlreadyOrdersRsp, error)
	// 进行评分
	OrderComment(context.Context, *OrderCommentReq) (*OrderCommentRsp, error)
}

// UnimplementedOrderServiceExtServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceExtServer struct {
}

func (*UnimplementedOrderServiceExtServer) WantTicket(context.Context, *WantTicketReq) (*WantTicketRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WantTicket not implemented")
}
func (*UnimplementedOrderServiceExtServer) Ticket(context.Context, *TicketReq) (*TicketRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ticket not implemented")
}
func (*UnimplementedOrderServiceExtServer) PayOrder(context.Context, *PayOrderReq) (*PayOrderRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayOrder not implemented")
}
func (*UnimplementedOrderServiceExtServer) UndoOrder(context.Context, *UndoOrderReq) (*UndoOrderRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndoOrder not implemented")
}
func (*UnimplementedOrderServiceExtServer) GetOrderMessage(context.Context, *GetOrderMessageReq) (*GetOrderMessageRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderMessage not implemented")
}
func (*UnimplementedOrderServiceExtServer) LookOrders(context.Context, *LookOrdersReq) (*LookOrdersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookOrders not implemented")
}
func (*UnimplementedOrderServiceExtServer) LookAlreadyOrders(context.Context, *LookAlreadyOrdersReq) (*LookAlreadyOrdersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookAlreadyOrders not implemented")
}
func (*UnimplementedOrderServiceExtServer) OrderComment(context.Context, *OrderCommentReq) (*OrderCommentRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderComment not implemented")
}

func RegisterOrderServiceExtServer(s *grpc.Server, srv OrderServiceExtServer) {
	s.RegisterService(&_OrderServiceExt_serviceDesc, srv)
}

func _OrderServiceExt_WantTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WantTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceExtServer).WantTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderServiceExt/WantTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceExtServer).WantTicket(ctx, req.(*WantTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderServiceExt_Ticket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceExtServer).Ticket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderServiceExt/Ticket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceExtServer).Ticket(ctx, req.(*TicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderServiceExt_PayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceExtServer).PayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderServiceExt/PayOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceExtServer).PayOrder(ctx, req.(*PayOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderServiceExt_UndoOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceExtServer).UndoOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderServiceExt/UndoOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceExtServer).UndoOrder(ctx, req.(*UndoOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderServiceExt_GetOrderMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceExtServer).GetOrderMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderServiceExt/GetOrderMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceExtServer).GetOrderMessage(ctx, req.(*GetOrderMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderServiceExt_LookOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceExtServer).LookOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderServiceExt/LookOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceExtServer).LookOrders(ctx, req.(*LookOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderServiceExt_LookAlreadyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookAlreadyOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceExtServer).LookAlreadyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderServiceExt/LookAlreadyOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceExtServer).LookAlreadyOrders(ctx, req.(*LookAlreadyOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderServiceExt_OrderComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceExtServer).OrderComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderServiceExt/OrderComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceExtServer).OrderComment(ctx, req.(*OrderCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderServiceExt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderServiceExt",
	HandlerType: (*OrderServiceExtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WantTicket",
			Handler:    _OrderServiceExt_WantTicket_Handler,
		},
		{
			MethodName: "Ticket",
			Handler:    _OrderServiceExt_Ticket_Handler,
		},
		{
			MethodName: "PayOrder",
			Handler:    _OrderServiceExt_PayOrder_Handler,
		},
		{
			MethodName: "UndoOrder",
			Handler:    _OrderServiceExt_UndoOrder_Handler,
		},
		{
			MethodName: "GetOrderMessage",
			Handler:    _OrderServiceExt_GetOrderMessage_Handler,
		},
		{
			MethodName: "LookOrders",
			Handler:    _OrderServiceExt_LookOrders_Handler,
		},
		{
			MethodName: "LookAlreadyOrders",
			Handler:    _OrderServiceExt_LookAlreadyOrders_Handler,
		},
		{
			MethodName: "OrderComment",
			Handler:    _OrderServiceExt_OrderComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
