// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"movie_gozero/api/order/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/wantTicket",
				Handler: wantTicketHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/ticket",
				Handler: ticketHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/payOrder",
				Handler: payOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/undoOrder",
				Handler: undoOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/getOrderMessage",
				Handler: getOrderMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/lookOrders",
				Handler: lookOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/lookAlreadyOrders",
				Handler: lookAlreadyOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/orderComment",
				Handler: orderCommentHandler(serverCtx),
			},
		},
	)
}
