// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"movie_gozero/api/cms/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cms/userLogin",
				Handler: userLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/updateMessage",
				Handler: updateMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allFilms",
				Handler: allFilmsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/updateFilm",
				Handler: updateFilmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/deleteFilm",
				Handler: deleteFilmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allUsers",
				Handler: allUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allAdminUsers",
				Handler: allAdminUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allComments",
				Handler: allCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allOrders",
				Handler: allOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allAddress",
				Handler: allAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/addFilm",
				Handler: addFilmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/addAdminUser",
				Handler: addAdminUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/addAddress",
				Handler: addAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/updateAddress",
				Handler: updateAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/deleteAddress",
				Handler: deleteAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/deleteAdminUser",
				Handler: deleteAdminUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allMovieHall",
				Handler: allMovieHallHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/addMovieHall",
				Handler: addMovieHallHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/updateMovieHall",
				Handler: updateMovieHallHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/deleteMovieHall",
				Handler: deleteMovieHallHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allCinemaFilms",
				Handler: allCinemaFilmsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/addCinemaFilm",
				Handler: addCinemaFilmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/updateCinemaFilm",
				Handler: updateCinemaFilmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/deleteCinemaFilm",
				Handler: deleteCinemaFilmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/registerCinema",
				Handler: registerCinemaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cms/allCinemaHall",
				Handler: allCinemaHallHandler(serverCtx),
			},
		},
	)
}
