// Code generated by goctl. DO NOT EDIT.
package types

type RegistAccountReq struct {
	Email    string `form:"email"`
	UserName string `form:"userName"`
	Password string `form:"password"`
}

type RegistAccountRsp struct {
}

type LoginAccountReq struct {
	Email    string `form:"email"`
	Password string `form:"password"`
}

type LoginAccountRsp struct {
	UserID   int64  `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
}

type ResetAccountReq struct {
}

type ResetAccountRsp struct {
}

type WantScoreReq struct {
	UserID  int64 `form:"userId"`
	MovieId int64 `form:"movieId"`
	Score   int64 `form:"score"`
}

type WantScoreRsp struct {
}

type UpdateUserProfileReq struct {
	UserImage string `form:"userImage"`
	UserName  string `form:"userName"`
	UserEmail string `form:"userEmail"`
	UserPhone string `form:"userPhone"`
	UserID    int64  `form:"userId"`
}

type UpdateUserProfileRsp struct {
}
