// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"movie_gozero/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/registAccount",
				Handler: registAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/loginAccount",
				Handler: loginAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/resetAccount",
				Handler: resetAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/wantScore",
				Handler: wantScoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/updateUserProfile",
				Handler: updateUserProfileHandler(serverCtx),
			},
		},
	)
}
