// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"movie_gozero/api/cinema/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cinema/locationCinema",
				Handler: locationCinemaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cinema/getCinemaMessageByCid",
				Handler: getCinemaMessageByCidHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cinema/getMovieHallByMHId",
				Handler: getMovieHallByMHIdHandler(serverCtx),
			},
		},
	)
}
