// Code generated by goctl. DO NOT EDIT!
// Source: cinema.proto

package server

import (
	"context"

	"movie_gozero/rpc/cinema/internal/logic"
	"movie_gozero/rpc/cinema/internal/svc"
	"movie_gozero/rpc/cinema/pb"
)

type CinemaServiceExtServer struct {
	svcCtx *svc.ServiceContext
}

func NewCinemaServiceExtServer(svcCtx *svc.ServiceContext) *CinemaServiceExtServer {
	return &CinemaServiceExtServer{
		svcCtx: svcCtx,
	}
}

//  地点影城
func (s *CinemaServiceExtServer) LocationCinema(ctx context.Context, in *pb.LocationCinemaReq) (*pb.LocationCinemaRsp, error) {
	l := logic.NewLocationCinemaLogic(ctx, s.svcCtx)
	return l.LocationCinema(in)
}

//  根据位置查看有销售对应电影的影院信息
func (s *CinemaServiceExtServer) GetCinemaMessageByCid(ctx context.Context, in *pb.GetCinemaMessageByCidReq) (*pb.GetCinemaMessageByCidRsp, error) {
	l := logic.NewGetCinemaMessageByCidLogic(ctx, s.svcCtx)
	return l.GetCinemaMessageByCid(in)
}

//  根据mh_id获取影厅信息
func (s *CinemaServiceExtServer) GetMovieHallByMHId(ctx context.Context, in *pb.GetMovieHallByMHIdReq) (*pb.GetMovieHallByMHIdRsp, error) {
	l := logic.NewGetMovieHallByMHIdLogic(ctx, s.svcCtx)
	return l.GetMovieHallByMHId(in)
}
