// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: place.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count       int64  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Id          int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	N           string `protobuf:"bytes,3,opt,name=n,proto3" json:"n,omitempty"`
	PinyinFull  string `protobuf:"bytes,4,opt,name=pinyinFull,proto3" json:"pinyinFull,omitempty"`
	PinyinShort string `protobuf:"bytes,5,opt,name=pinyinShort,proto3" json:"pinyinShort,omitempty"`
}

func (x *Place) Reset() {
	*x = Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{0}
}

func (x *Place) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Place) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Place) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *Place) GetPinyinFull() string {
	if x != nil {
		return x.PinyinFull
	}
	return ""
}

func (x *Place) GetPinyinShort() string {
	if x != nil {
		return x.PinyinShort
	}
	return ""
}

type HotCitiesByCinemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HotCitiesByCinemaReq) Reset() {
	*x = HotCitiesByCinemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotCitiesByCinemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotCitiesByCinemaReq) ProtoMessage() {}

func (x *HotCitiesByCinemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotCitiesByCinemaReq.ProtoReflect.Descriptor instead.
func (*HotCitiesByCinemaReq) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{1}
}

type HotCitiesByCinemaRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P []*Place `protobuf:"bytes,1,rep,name=p,proto3" json:"p,omitempty"`
}

func (x *HotCitiesByCinemaRep) Reset() {
	*x = HotCitiesByCinemaRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_place_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotCitiesByCinemaRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotCitiesByCinemaRep) ProtoMessage() {}

func (x *HotCitiesByCinemaRep) ProtoReflect() protoreflect.Message {
	mi := &file_place_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotCitiesByCinemaRep.ProtoReflect.Descriptor instead.
func (*HotCitiesByCinemaRep) Descriptor() ([]byte, []int) {
	return file_place_proto_rawDescGZIP(), []int{2}
}

func (x *HotCitiesByCinemaRep) GetP() []*Place {
	if x != nil {
		return x.P
	}
	return nil
}

var File_place_proto protoreflect.FileDescriptor

var file_place_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x22, 0x7d, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x69, 0x6e, 0x79, 0x69, 0x6e, 0x46, 0x75, 0x6c, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69, 0x6e, 0x79, 0x69, 0x6e, 0x46, 0x75, 0x6c,
	0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x69, 0x6e, 0x79, 0x69, 0x6e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x69, 0x6e, 0x79, 0x69, 0x6e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x48, 0x6f, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x42, 0x79, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x22, 0x32, 0x0a, 0x14, 0x48,
	0x6f, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x79, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x52, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x01, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x01, 0x70, 0x32,
	0x60, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45,
	0x78, 0x74, 0x12, 0x4d, 0x0a, 0x11, 0x48, 0x6f, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42,
	0x79, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e,
	0x48, 0x6f, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x79, 0x43, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x48, 0x6f, 0x74,
	0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x79, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65,
	0x70, 0x42, 0x04, 0x5a, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_place_proto_rawDescOnce sync.Once
	file_place_proto_rawDescData = file_place_proto_rawDesc
)

func file_place_proto_rawDescGZIP() []byte {
	file_place_proto_rawDescOnce.Do(func() {
		file_place_proto_rawDescData = protoimpl.X.CompressGZIP(file_place_proto_rawDescData)
	})
	return file_place_proto_rawDescData
}

var file_place_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_place_proto_goTypes = []interface{}{
	(*Place)(nil),                // 0: place.Place
	(*HotCitiesByCinemaReq)(nil), // 1: place.HotCitiesByCinemaReq
	(*HotCitiesByCinemaRep)(nil), // 2: place.HotCitiesByCinemaRep
}
var file_place_proto_depIdxs = []int32{
	0, // 0: place.HotCitiesByCinemaRep.p:type_name -> place.Place
	1, // 1: place.PlaceServiceExt.HotCitiesByCinema:input_type -> place.HotCitiesByCinemaReq
	2, // 2: place.PlaceServiceExt.HotCitiesByCinema:output_type -> place.HotCitiesByCinemaRep
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_place_proto_init() }
func file_place_proto_init() {
	if File_place_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_place_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotCitiesByCinemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_place_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotCitiesByCinemaRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_place_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_place_proto_goTypes,
		DependencyIndexes: file_place_proto_depIdxs,
		MessageInfos:      file_place_proto_msgTypes,
	}.Build()
	File_place_proto = out.File
	file_place_proto_rawDesc = nil
	file_place_proto_goTypes = nil
	file_place_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlaceServiceExtClient is the client API for PlaceServiceExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaceServiceExtClient interface {
	// 获取所有电影院的地点
	HotCitiesByCinema(ctx context.Context, in *HotCitiesByCinemaReq, opts ...grpc.CallOption) (*HotCitiesByCinemaRep, error)
}

type placeServiceExtClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaceServiceExtClient(cc grpc.ClientConnInterface) PlaceServiceExtClient {
	return &placeServiceExtClient{cc}
}

func (c *placeServiceExtClient) HotCitiesByCinema(ctx context.Context, in *HotCitiesByCinemaReq, opts ...grpc.CallOption) (*HotCitiesByCinemaRep, error) {
	out := new(HotCitiesByCinemaRep)
	err := c.cc.Invoke(ctx, "/place.PlaceServiceExt/HotCitiesByCinema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaceServiceExtServer is the server API for PlaceServiceExt service.
type PlaceServiceExtServer interface {
	// 获取所有电影院的地点
	HotCitiesByCinema(context.Context, *HotCitiesByCinemaReq) (*HotCitiesByCinemaRep, error)
}

// UnimplementedPlaceServiceExtServer can be embedded to have forward compatible implementations.
type UnimplementedPlaceServiceExtServer struct {
}

func (*UnimplementedPlaceServiceExtServer) HotCitiesByCinema(context.Context, *HotCitiesByCinemaReq) (*HotCitiesByCinemaRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HotCitiesByCinema not implemented")
}

func RegisterPlaceServiceExtServer(s *grpc.Server, srv PlaceServiceExtServer) {
	s.RegisterService(&_PlaceServiceExt_serviceDesc, srv)
}

func _PlaceServiceExt_HotCitiesByCinema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HotCitiesByCinemaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceServiceExtServer).HotCitiesByCinema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/place.PlaceServiceExt/HotCitiesByCinema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceServiceExtServer).HotCitiesByCinema(ctx, req.(*HotCitiesByCinemaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaceServiceExt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "place.PlaceServiceExt",
	HandlerType: (*PlaceServiceExtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HotCitiesByCinema",
			Handler:    _PlaceServiceExt_HotCitiesByCinema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "place.proto",
}
