// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"movie_gozero/api/comment/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comment/hotComment",
				Handler: hotCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/makeComment",
				Handler: makeCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/upNumComment",
				Handler: upNumCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/myComments",
				Handler: myCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/deleteComment",
				Handler: deleteCommentHandler(serverCtx),
			},
		},
	)
}
