// Code generated by goctl. DO NOT EDIT.
package types

type WantTicketReq struct {
	UserId int64 `form:"userId"`
	FilmId int64 `form:"filmId"`
	Type   int64 `form:"type"`
}

type WantTicketRsp struct {
}

type TicketReq struct {
	UserId    int64  `form:"userId"`
	FilmId    int64  `form:"filmId"`
	MhId      int64  `form:"mhId"`
	X         int64  `form:"x"`
	Y         int64  `form:"y"`
	StartTime string `form:"startTime"`
	EndTime   string `form:"endTime"`
}

type TicketRsp struct {
	OrderNumD int64 `json:"orderNumD"`
}

type Order struct {
	OrderNum   string `json:"orderNum"`
	OrderPrice string `json:"orderPrice"`
	CreateAt   string `json:"createAt"`
	PayAt      string `json:"payAt"`
	MhId       int64  `json:"mhId"`
	UserId     int64  `json:"userId"`
	MovieId    int64  `json:"movieId"`
}

type MovieTicket struct {
	FilmName  string `json:"filmName"`
	StartTime string `json:"startTime"`
	Cinema    string `json:"cinema"`
	OrderNum  string `json:"orderNum"`
}

type LookOrdersReq struct {
	UserId int64 `form:"userId"`
}

type LookOrdersRsp struct {
	MovieTickets []*MovieTicket `json:"movieTickets"`
}

type PayOrderReq struct {
	OrderNum string `form:"orderNum"`
	UserId   int64  `form:"userId"`
	Phone    int64  `form:"phone"`
}

type PayOrderRsp struct {
}

type UndoOrderReq struct {
	OrderId int64 `form:"orderId"`
}

type UndoOrderRsp struct {
}

type GetOrderMessageReq struct {
	OrderNum string `form:"orderNum"`
	UserId   int64  `form:"userId"`
}

type GetOrderMessageRsp struct {
	Ticketdetail TicketDetail `json:"ticketdetail"`
}

type TicketDetail struct {
	FilmName      string  `json:"filmName"`
	FilmImg       string  `json:"filmImg"`
	StartTime     string  `json:"startTime"`
	EndTime       string  `json:"endTime"`
	CinemaName    string  `json:"cinemaName"`
	MhName        string  `json:"mhName"`
	Seat          string  `json:"seat"`
	OrderNum      string  `json:"orderNum"`
	CinemaAddress string  `json:"cinemaAddress"`
	Price         float64 `json:"price"`
	CreateAt      string  `json:"createAt"`
	Phone         int64   `json:"phone"`
	CinemaPhone   int64   `json:"cinemaPhone"`
}

type LookAlreadyOrdersReq struct {
	UserId int64 `form:"userId"`
}

type LookAlreadyOrdersRsp struct {
	TotalMovie   int64           `json:"totalMovie"`
	OneNoComment int64           `json:"oneNoComment"`
	Movies       []*AlreadyMovie `json:"movies"`
}

type AlreadyMovie struct {
	FilmImg    string   `json:"filmImg"`
	FilmName   string   `json:"filmName"`
	Time       string   `json:"time"`
	Director   string   `json:"director"`
	ActorNames []string `json:"actorNames"`
	OrderNum   string   `json:"orderNum"`
}

type OrderCommentReq struct {
	UserId         int64  `form:"userId"`
	Score          int64  `form:"score"`
	CommentContent string `form:"commentContent"`
	OrderNum       string `form:"orderNum"`
	MovieId        int64  `form:"movieId"`
}

type OrderCommentRsp struct {
}
